name = "Awesome Canada"
license = "MIT"
licenselink = "https://github.com/julienandreu/hugo-theme-awesome-canada/blob/master/LICENSE"
description = "A minimalist Hugo theme"
homepage = "https://github.com/julienandreu/hugo-theme-awesome-canada/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'awesome', 'canada', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Julien Andreu"
  homepage = "https://www.julienandreu.fr/"